// Additional light themes. Same shape as the entries in themes.cjs.
module.exports = [
  {
    id: "paper",
    name: "Paper",
    scheme: "light",
    colors: {
      page: "#f2f2f3",
      surface: "#ffffff",
      surface2: "#ebebec",
      line: "#e0e0e2",
      lineStrong: "#c5c5c9",
      text: "#111113",
      text2: "#48484d",
      text3: "#66666b",
      accent: "#1d63d6",
    },
  },
  {
    id: "sepia",
    name: "Sepia",
    scheme: "light",
    colors: {
      page: "#eee4cf",
      surface: "#fbf6e9",
      surface2: "#f0e6d0",
      line: "#e0d3b6",
      lineStrong: "#c8b791",
      text: "#2e2013",
      text2: "#5a4631",
      text3: "#725c43",
      accent: "#b4471f",
    },
  },
  {
    id: "mist",
    name: "Mist",
    scheme: "light",
    colors: {
      page: "#e7edf4",
      surface: "#f8fafd",
      surface2: "#e7edf5",
      line: "#d6dfea",
      lineStrong: "#b9c6d6",
      text: "#162030",
      text2: "#43536a",
      text3: "#5b6c83",
      accent: "#2563c9",
    },
  },
  {
    id: "sage",
    name: "Sage",
    scheme: "light",
    colors: {
      page: "#e6ede4",
      surface: "#f8fbf6",
      surface2: "#e8efe3",
      line: "#d6e0d1",
      lineStrong: "#b9c9b3",
      text: "#13231a",
      text2: "#3e5345",
      text3: "#586d5f",
      accent: "#2a7a4b",
    },
  },
  {
    id: "blossom",
    name: "Blossom",
    scheme: "light",
    colors: {
      page: "#f5e8eb",
      surface: "#fffafb",
      surface2: "#f8e8ec",
      line: "#ebd5db",
      lineStrong: "#d6b6c0",
      text: "#2b1520",
      text2: "#5b3c4a",
      text3: "#785866",
      accent: "#c0306b",
    },
  },
  {
    id: "bubblegum",
    name: "Bubblegum",
    scheme: "light",
    colors: {
      page: "#ffd9e8",
      surface: "#fff4f9",
      surface2: "#ffdcea",
      line: "#fbc3d9",
      lineStrong: "#f29dc0",
      text: "#3d0f29",
      text2: "#6e2d4d",
      text3: "#8a4566",
      accent: "#e0387f",
    },
  },
];
